### PR TITLE
Add Oxocarbon Dark theme

### PR DESCRIPTION
**Pull request by xstyyy**
Adds the dark version of the [Oxocarbon](https://github.com/nyoom-engineering/oxocarbon) theme

Preview:
Screenshot of Lite-XL with Oxocarbon Dark theme

### CODE REVIEW

**Comment by Guldoman** [comment]
There might be a problem with your PR, the colors from the screenshot don't really match with the ones here.

**Comment by xstyyy** [comment]
> There might be a problem with your PR, the colors from the screenshot don't really match with the ones here.

oh yeah my bad, I uploaded out the wrong version

**Review by Guldoman — APPROVED** [review]
Looks good!
Only nit, could you move the entry in the manifest under `only_dark`?

**Comment by xstyyy** [comment]
> Looks good! Only nit, could you move the entry in the manifest under `only_dark`?

Sure

**Comment by Guldoman** [comment]
Thank you!

**Pull request merged**
