### PR TITLE
New colorscheme und local preview directory

### PR DESCRIPTION
**Pull request by proskur1n**
1. New dark colorscheme based on GitHub palette
2. I think that the previews should be stored locally in this repository. This makes it easier to maintain and contribute new themes. I have not moved other images yet.

### CODE REVIEW

**Comment by adamharrison** [comment]
1. This looks great.
2. This is a good point. I think you're right, it does make sense; but I'll wait for someone else to concur before I merge this.

**Comment by Jan200101** [comment]
One small problem with 2. is that Images are not something git deals very well with

**Comment by jgmdev** [comment]
> One small problem with 2. is that Images are not something git deals very well with

Maybe svg files could be generated instead.

**Comment by liquidev** [comment]
I second jgmdev's idea, though while we're at it maybe we could generate an SVG that is basically a preview of how it would look in the editor? As in, showing off all the syntax highlighting groups. It would make picking a theme much easier.

**Comment by krthknch** [comment]
I've converted all the PNGs to SVGs and edited the generator script in #9.
Maybe @liquidev's idea can be a future project.

**Comment by jgmdev** [comment]
@proskur1n now that #9 is merged can you rebase your pull request on master to just include the new theme?

**Comment by jgmdev** [comment]
Manually applied this pull request to master: https://github.com/lite-xl/lite-xl-colors/commit/96aa1e80bf38f81a8557458dd07dce4221c1a56f

**Pull request closed without merging**
