### PR TITLE
rename monokai to monokai-pro, add mariana and monokai from Sublime

### PR DESCRIPTION
**Pull request by Jan200101**
the monokai color scheme has had many derivites and changes over the years.

Renamed the monokai to monokai-pro-classic
Added Monokai and Mariana themes from Sublime Text 4

styles are from this commit https://github.com/Jan200101/lite-lime/commit/ba8c5fa0438f110db6e962e8b94c128a6b53ec71

Comparions to their Sublime counterparts

Mariana
image

Monokai
image

Monokai-Pro Classic
image

### CODE REVIEW

**Comment by liquidev** [comment]
The theme you call monokai-pro looks to me like Monokai Pro's "Classic" variant, which isn't the same as Monokai Pro's default variant. See: https://monokai.pro/vscode

**Comment by Jan200101** [comment]
> The theme you call monokai-pro looks to me like Monokai Pro's "Classic" variant, which isn't the same as Monokai Pro's default variant. See: https://monokai.pro/vscode

I am aware, but what do you suggest?
Renaming it to monokai-pro-classic?

**Comment by liquidev** [comment]
That would make the most sense to me, but I see why you'd want the name to be `monokai-pro` – we don't have any of the other Monokai Pro variants available.

In my opinion we should keep the theme names in line with what they are called by their authors, such that they're easily discoverable and don't confuse users (eg. if they'd expect our `monokai-pro` to be _the_ Monokai Pro, which it isn't.)

**Comment by liquidev** [comment]
An alternative would be to add a `Notes` column to the table of themes, that could include additional info like a link to the original theme, as well as differences like this one if we choose to keep the `monokai-pro` name. This of course would be in a separate PR so as to keep all PRs focused on one thing.

**Pull request merged**
