### PR TITLE
Svg preview

### PR DESCRIPTION
**Pull request by krthknch**
As discussed in #3, 
- Modified the `make_preview_image.lua` file to create SVGs instead of PNGs
- Added local `previews` directory
- Updated all existing previews to SVGs in README

### CODE REVIEW

**Comment by jgmdev** [comment]
Excellent! My suggestion would be to not append a `_preview` to the svg files since they are already stored on the previews directory, making their names unnecessary long, unless you are planning on generating multiple types of previews for a color theme (like a svg mockup of the editor with the colors of the theme applied). Everything else looks great.

**Comment by krthknch** [comment]
Done!

**Comment by jgmdev** [comment]
You forgot to `git rm` all the `previews/*_preview.svg` files and also would be nice to prepend the preview directory on `local fp = io.open("previews/" .. name .. ".svg", "wb")` so they are directly stored on the previews directory.

**Comment by krthknch** [comment]
Sorry! Still learning git. Should be solved now.

**Comment by jgmdev** [comment]
Thanks!

**Pull request merged**
